---
- name: Check if ProxyChains is installed
  ansible.builtin.command:
    cmd: proxychains4 --help
  register: proxychains4_output
  ignore_errors: true
  changed_when: false
  tags: proxychains_ng

- name: Set proxychains_installed if command returns 'Usage:'
  ansible.builtin.set_fact:
    proxychains_installed: true
  when: "'Usage:' in proxychains4_output.stdout"
  tags: proxychains_ng

- name: Get the installed version string from the repository
  ansible.builtin.slurp:
    src: "{{ sources_dir }}/proxychains-ng/VERSION"
  register: installed_proxychains_version_contents
  when: proxychains_installed
  tags: proxychains_ng

- name: Decode the file contents to a fact
  ansible.builtin.set_fact:
    installed_proxychains_version: "{{ installed_proxychains_version_contents.content | b64decode | trim }}"
  when: installed_proxychains_version_contents
  tags: proxychains_ng

- name: Fetch tags and force update if ProxyChains directory exists
  ansible.builtin.command:
    cmd: git fetch --tags --force
  args:
    chdir: "{{ sources_dir }}/proxychains-ng"
  when:
    - proxychains_installed
    - installed_proxychains_version
  ignore_errors: true
  changed_when: false
  tags: proxychains_ng

- name: Clone the ProxyChains repository
  ansible.builtin.git:
    repo: https://github.com/rofl0r/proxychains-ng.git
    dest: "{{ sources_dir }}/proxychains-ng"
    version: master
    update: true
  tags: proxychains_ng

- name: Get the latest stable version tag from the ProxyChains repo
  ansible.builtin.command:
    cmd: git describe --tags --abbrev=0
  args:
    chdir: "{{ sources_dir }}/proxychains-ng"
  register: latest_proxychains_version
  changed_when: false
  tags: proxychains_ng

- name: Remove the leading 'v' from the latest_proxychains_version
  ansible.builtin.set_fact:
    latest_proxychains_version_clean: "{{ latest_proxychains_version.stdout | regex_replace('^v', '') }}"
  tags: proxychains_ng

- name: Build ProxyChains if not installed or version mismatch
  community.general.make:
    chdir: "{{ sources_dir }}/proxychains-ng"
  when: installed_proxychains_version is not defined or installed_proxychains_version != latest_proxychains_version_clean
  tags: proxychains_ng

- name: Install ProxyChains
  become: true
  community.general.make:
    chdir: "{{ sources_dir }}/proxychains-ng"
    target: install
  when: installed_proxychains_version is not defined or installed_proxychains_version != latest_proxychains_version_clean
  tags: proxychains_ng

- name: Install ProxyChains config
  become: true
  ansible.builtin.template:
    src: templates/proxychains.conf.j2
    dest: /etc/proxychains.conf
    owner: root
    group: root
    mode: '0664'
  tags: proxychains_ng
