---
- name: Ensure {{ ansible_env.HOME }}/repos exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/repos"
    state: directory
    mode: '0755'
  tags: dotfiles

- name: Install dotfiles
  ansible.builtin.git:
    repo: https://github.com/ryanreece/dotfiles.git
    dest: "{{ ansible_env.HOME }}/repos/dotfiles"
    update: true
  tags: dotfiles

- name: Make install_dotfiles.sh executable
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/repos/dotfiles/install_dotfiles.sh"
    mode: '0755'
  tags: dotfiles

- name: Run install_dotfiles.sh
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/repos/dotfiles/install_dotfiles.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/repos/dotfiles"
  changed_when: false
  tags: dotfiles

- name: Collect facts and source dotfiles
  ansible.builtin.setup:
  tags: dotfiles
