---
- name: Install Neovim dependencies 
  become: true
  ansible.builtin.package:
    name:
      - gnupg
      - gpg
      - gpg-agent
      - ripgrep
      - xclip
      - xsel
  tags: neovim

- name: Check if Neovim is installed
  ansible.builtin.command:
    cmd: nvim --version
  register: neovim_installed
  ignore_errors: true
  changed_when: false
  tags: neovim

- name: Set the installed Neovim version
  ansible.builtin.set_fact:
    installed_neovim_version: "{{ neovim_installed.stdout_lines[0] | regex_search('NVIM v([0-9.]+)', '\\1') | first }}"
  when: neovim_installed.rc == 0
  tags: neovim

- name: Fetch tags and force update if Neovim directory exists
  ansible.builtin.command:
    cmd: git fetch --tags --force
  args:
    chdir: "{{ sources_dir }}/neovim"
  when: neovim_installed.rc == 0
  ignore_errors: true
  changed_when: false
  tags: neovim

- name: Clone the Neovim repository
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: "{{ sources_dir }}/neovim"
    version: stable
    update: true
  tags: neovim

- name: Get the latest stable version tag from the Neovim repo
  ansible.builtin.command:
    cmd: git describe --tags --abbrev=0
  args:
    chdir: "{{ sources_dir }}/neovim"
  register: latest_neovim_version
  changed_when: false
  tags: neovim

- name: Remove the leading 'v' from the latest_neovim_version
  ansible.builtin.set_fact:
    latest_neovim_version_clean: "{{ latest_neovim_version.stdout | regex_replace('^v', '') }}"
  tags: neovim

- name: Build Neovim if not installed or version mismatch
  community.general.make:
    chdir: "{{ sources_dir }}/neovim"
    params:
      CMAKE_BUILD_TYPE: Release
  when: installed_neovim_version is not defined or installed_neovim_version != latest_neovim_version_clean
  tags: neovim

- name: Install Neovim
  become: true
  community.general.make:
    chdir: "{{ sources_dir }}/neovim"
    target: install
  when: installed_neovim_version is not defined or installed_neovim_version != latest_neovim_version_clean
  tags: neovim

- name: Install Neovim config
  ansible.builtin.git:
    repo: https://github.com/ryanreece/neovim-config.git
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    update: true
  tags: neovim
