---
- name: Set workstation system facts
  ansible.builtin.include_tasks:
    file: set_facts.yml
  tags: always

- name: Install essential libraries
  ansible.builtin.include_tasks:
    file: install_libraries.yml
  when: install_libraries | default(true)
  tags: libraries

- name: Install python
  ansible.builtin.include_tasks:
    file: install_python.yml
  when: install_python | default(true)
  tags: python

- name: Install TypeScript
  ansible.builtin.include_tasks:
    file: install_typescript.yml
  when: install_typescript | default(true)
  tags: typescript

- name: Install luarocks
  ansible.builtin.include_tasks:
    file: install_luarocks.yml
  when: install_luarocks | default(true)
  tags: luarocks

- name: Install Neovim
  ansible.builtin.include_tasks:
    file: install_neovim.yml
  when: install_neovim | default(true)
  tags: neovim

- name: Install dotfiles
  ansible.builtin.include_tasks:
    file: install_dotfiles.yml
  when: install_dotfiles | default(true)
  tags: dotfiles

- name: Install fastfetch
  ansible.builtin.include_tasks:
    file: install_fastfetch.yml
  when: install_fastfetch | default(true)
  tags: fastfetch

- name: Install docker
  ansible.builtin.include_tasks:
    file: install_docker.yml
  when: install_docker | default(true)
  tags: docker

- name: Install lazydocker
  ansible.builtin.include_tasks:
    file: install_lazydocker.yml
  when: install_lazydocker | default(true)
  tags: lazydocker

- name: Install lazygit
  ansible.builtin.include_tasks:
    file: install_lazygit.yml
  when: install_lazygit | default(true)
  tags: lazygit

- name: Install minicom
  ansible.builtin.include_tasks:
    file: install_minicom.yml
  when: install_minicom | default(true)
  tags: minicom

- name: Install terraform
  ansible.builtin.include_tasks:
    file: install_terraform.yml
  when: install_terraform | default(true)
  tags: terraform
