---
- name: Deploy Ansible
  hosts: linux
  vars:
    ansible_user: sysadmin

  tasks:
  - name: Ensure dependencies are present.
    become: yes
    ansible.builtin.apt:
      name:
        - software-properties-common
      state: present

  - name: Install ppa:ansible/ansible apt_repository
    become: yes
    ansible.builtin.apt_repository:
      repo: ppa:ansible/ansible

  - name: Update all packages to the latest version
    become: yes
    ansible.builtin.apt:
      upgrade: dist

  - name: Install Ansible
    become: yes
    ansible.builtin.apt:
      name:
        - ansible
      state: present
