---
sources_dir: "{{ ansible_env.HOME }}/sources"

# Install variables
# These variables define which include_tasks will run for the workstation role.
install_dotfiles: true
install_libraries: true
install_luarocks: true
install_neovim: true
install_python: true
install_go: true
install_typescript: true
install_ruby: true
install_fastfetch: true
install_docker: true
install_cloud_utilities: true
install_cisco_secure_client: true
install_proxychains_ng: true
install_lazydocker: true
install_lazygit: true
install_minicom: true
install_terraform: true
install_powershell: true
