---
nodejs_version: 20.17.0
nvm_version: v0.40.1
ohmyzsh_theme: robbyrussell
openssh_keypair_type: ed25519

# Install variables
install_packages: true
install_tmux: true
install_zsh: true
install_ssh_key: true
install_nodejs: true
install_aws_cli: true
