---
- name: Install required system packages for docker
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'
  tags: docker

- name: Add docker gpg apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags: docker

- name: Add docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags: docker

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-ce-rootless-extras
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags: docker

- name: Add {{ ansible_user_id }} to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  tags: docker
