---
- name: Install python3 and common packages
  become: true
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - python3-pylsp
      - python3-venv
      - python-is-python3
    state: present 
  tags: python
