---
- name: Add fastfetch apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:zhangsongcui3371/fastfetch'
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags: fastfetch

- name: Install fastfetch
  become: true
  ansible.builtin.package:
    name:
      - fastfetch
    state: present
  tags: fastfetch
