---
- name: Install dotfiles
  ansible.builtin.git:
    repo: https://github.com/ryanreece/dotfiles.git
    dest: "{{ ansible_env.HOME }}/dotfiles"
    update: true
  tags: dotfiles

- name: Make the install_dotfiles.sh script executable
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/dotfiles/install_dotfiles.sh"
    mode: '0755'
  tags: dotfiles

- name: Run the install_dotfiles.sh script
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/dotfiles/install_dotfiles.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles"
  tags: dotfiles
