---
- name: Install compilation packages
  ansible.builtin.include_tasks:
    file: install_packages.yml
  when: install_packages | default(true)
  tags: packages

- name: Install python
  ansible.builtin.include_tasks:
    file: install_python.yml
  when: install_python | default(true)
  tags: python

- name: Install Neovim
  ansible.builtin.include_tasks:
    file: install_neovim.yml
  when: install_neovim | default(true)
  tags: neovim

- name: Install dotfiles
  ansible.builtin.include_tasks:
    file: install_dotfiles.yml
  when: install_dotfiles | default(true)
  tags: dotfiles

- name: Install Alacritty
  ansible.builtin.include_tasks:
    file: install_alacritty.yml
  when: install_alacritty | default(true)
  tags: alacritty

- name: Install flameshot
  ansible.builtin.include_tasks:
    file: install_flameshot.yml
  when: install_flameshot | default(true)
  tags: flameshot

- name: Install Regolith
  ansible.builtin.include_tasks:
    file: install_regolith.yml
  when: install_regolith | default(true)
  tags: regolith

- name: Install TypeScript
  ansible.builtin.include_tasks:
    file: install_typescript.yml
  when: install_typescript | default(true)
  tags: typescript
