---
- name: Deploy server .zshrc
  ansible.builtin.template:
    src: templates/zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0640'
  tags: zsh
