---
- name: Set server hostname
  ansible.builtin.include_tasks:
    file: set_hostname.yml
  when: install_server_hostname | default(true)
  tags: hostname

- name: Upgrade server packages
  ansible.builtin.include_tasks:
    file: upgrade_packages.yml
  when: install_server_package_upgrades | default(true)
  tags: packages

- name: Configure unattended server updates
  ansible.builtin.include_tasks:
    file: configure_unattended_updates.yml
  when: install_server_unattended_updates | default(true)
  tags: unattended_updates

- name: Deploy server tmux config
  ansible.builtin.include_tasks:
    file: deploy_tmux_config.yml
  when: install_server_tmux_config | default(true)
  tags: tmux

- name: Deploy server zsh config
  ansible.builtin.include_tasks:
    file: deploy_zsh_config.yml
  when: install_server_zsh_config | default(true)
  tags: zsh
