---
- name: Check if Chrome is installed
  ansible.builtin.command:
    cmd: google-chrome --version
  register: chrome_installed
  ignore_errors: true
  changed_when: false
  tags: chrome

- name: Download Chrome deb package
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
  when:
    - ansible_facts['os_family'] == 'Debian'
    - chrome_installed.rc != 0
  tags: chrome

- name: Import Google GPG key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.google.com/linux/linux_signing_key.pub
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - chrome_installed.rc != 0
  tags: chrome

- name: Download Chrome rpm package
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    dest: /tmp/google-chrome-stable_current_x86_64.rpm
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - chrome_installed.rc != 0
  tags: chrome

- name: Install Chrome on Debian os families
  become: true
  ansible.builtin.apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  when:
    - ansible_facts['os_family'] == 'Debian'
    - chrome_installed.rc != 0
  tags: chrome

- name: Install Chrome on RedHat os families
  become: true
  ansible.builtin.dnf:
    name: /tmp/google-chrome-stable_current_x86_64.rpm
    state: present
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - chrome_installed.rc != 0
  tags: chrome

- name: Remove Chrome deb package
  ansible.builtin.file:
    path: /tmp/google-chrome-stable_current_amd64.deb
    state: absent
  when:
    - ansible_facts['os_family'] == 'Debian'
    - chrome_installed.rc != 0
  tags: chrome

- name: Remove Chrome rpm package
  ansible.builtin.file:
    path: /tmp/google-chrome-stable_current_x86_64.rpm
    state: absent
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - chrome_installed.rc != 0
  tags: chrome
