---
- name: Add universe repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    state: present
  tags: ulauncher

- name: Add ulauncher repository
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:agornostal/ulauncher"
    state: present
  tags: ulauncher

- name: Install ulauncher
  become: true
  ansible.builtin.apt:
    name: ulauncher
    state: present
  tags: ulauncher
