---
- name: Install flameshot for supported os families
  become: true
  ansible.builtin.package:
    name:
      - flameshot
    state: present
  when: ansible_facts['os_family'] in ['Debian', 'RedHat', 'Archlinux']
  tags: flameshot
