---
- name: Install Alacritty
  ansible.builtin.include_tasks:
    file: install_alacritty.yml
  when: install_alacritty | default(true)
  tags: alacritty

- name: Install flameshot
  ansible.builtin.include_tasks:
    file: install_flameshot.yml
  when: install_flameshot | default(true)
  tags: flameshot

- name: Install Regolith
  ansible.builtin.include_tasks:
    file: install_regolith.yml
  when: install_regolith | default(true)
  tags: regolith

- name: Install Chrome
  ansible.builtin.include_tasks:
    file: install_chrome.yml
  when: install_chrome | default(true)
  tags: chrome

- name: Install ulauncher
  ansible.builtin.include_tasks:
    file: install_ulauncher.yml
  when: install_ulauncher | default(true)
  tags: ulauncher
