---
- name: Install Alacritty
  ansible.builtin.include_tasks:
    file: install_alacritty.yml
  when: install_alacritty | default(true)
  tags: alacritty

- name: Install flameshot
  ansible.builtin.include_tasks:
    file: install_flameshot.yml
  when: install_flameshot | default(true)
  tags: flameshot

- name: Install Regolith
  ansible.builtin.include_tasks:
    file: install_regolith.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_regolith | default(true)
  tags: regolith

- name: Install Chrome
  ansible.builtin.include_tasks:
    file: install_chrome.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_chrome | default(true)
  tags: chrome

- name: Install Microsoft keyring
  ansible.builtin.include_tasks:
    file: install_microsoft_keyring.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_microsoft_edge | default(true) or
      install_vscode | default(true)
  tags:
    - microsoft_edge
    - vscode

- name: Install Microsoft Edge
  ansible.builtin.include_tasks:
    file: install_microsoft_edge.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_microsoft_edge | default(true)
  tags: microsoft_edge

- name: Install VSCode
  ansible.builtin.include_tasks:
    file: install_vscode.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_vscode | default(true)
  tags: vscode

- name: Install ulauncher
  ansible.builtin.include_tasks:
    file: install_ulauncher.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_ulauncher | default(true)
  tags: ulauncher

- name: Install Remmina
  ansible.builtin.include_tasks:
    file: install_remmina.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_remmina | default(true)
  tags: remmina

- name: Install KeePassXC
  ansible.builtin.include_tasks:
    file: install_keepassxc.yml
  when:
    - ansible_facts['os_family'] == 'Debian'
    - install_remmina | default(true)
  tags: keepassxc
