---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags: hostname

- name: Update all packages to the latest version
  become: true
  ansible.builtin.apt:
    upgrade: dist
  register: apt_upgrade_result
  when: ansible_facts['os_family'] == 'Debian'
  notify:
    - Reboot system
  tags: apt
