---
- name: Deploy Zabbix Agent 2 configuration
  become: true
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: '0640'
  notify: Restart zabbix-agent2
  tags: zabbix_agent

- name: Enable and start Zabbix Agent 2 service
  become: true
  ansible.builtin.systemd_service:
    name: zabbix-agent2
    state: started
    enabled: true
  tags: zabbix_agent
