---
- name: Install the EPEL repository
  ansible.builtin.include_role:
    name: geerlingguy.repo-epel
  vars:
    ansible_become: true

- name: Update the package cache
  become: true
  ansible.builtin.package:
    update_cache: true

- name: Install snapd
  become: true
  ansible.builtin.dnf:
    name: snapd
    state: present

- name: Enable snapd socket
  become: true
  ansible.builtin.systemd_service:
    name: snapd.socket
    state: started
    enabled: true

- name: Create class snap symlink
  become: true
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
