---
- name: Install packages
  ansible.builtin.include_tasks:
    file: install_packages.yml
  when: install_packages | default(true)
  tags: packages

- name: Install tmux
  ansible.builtin.include_tasks:
    file: install_tmux.yml
  when: install_tmux | default(true)
  tags: tmux

- name: Install zsh
  ansible.builtin.include_tasks:
    file: install_zsh.yml
  when: install_zsh | default(true)
  tags: zsh

- name: Install SSH key
  ansible.builtin.include_tasks:
    file: install_ssh_key.yml
  when: install_ssh_key | default(true)
  tags: ssh

- name: Install NodeJS via nvm
  ansible.builtin.include_tasks:
    file: install_nodejs.yml
  when: install_nodejs | default(true)
  tags: nodejs

- name: Install AWS CLI
  ansible.builtin.include_tasks:
    file: install_aws_cli.yml
  when: install_aws_cli | default(true)
  tags: aws
