---
- name: Create NFS mount point directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
  loop: "{{ nfs_client_mounts }}"
  tags: nfs_client_mounts

- name: Mount NFS shares and persist in fstab
  become: true
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: "{{ item.opts }}"
    state: mounted
  loop: "{{ nfs_client_mounts }}"
  tags: nfs_client_mounts
