---
- name: Install NFS client packages (RedHat)
  become: true
  ansible.builtin.dnf:
    name: nfs-utils
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags: nfs_client_packages

- name: Install NFS client packages (Debian)
  become: true
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: false
  when: ansible_facts['os_family'] == 'Debian'
  tags: nfs_client_packages
